export const LOAD_ASSETS = 'LOAD_ASSETS';
export const LOAD_ASSETS_PROGRESS = 'LOAD_ASSETS_PROGRESS';
export const LOAD_ASSETS_LOADED = 'LOAD_ASSETS_LOADED';
export const SWITCH_OBJECT = 'SWITCH_OBJECT';
export const SWITCH_WEBSITE_READY = 'SWITCH_WEBSITE_READY';
export const SWITCH_CURSOR_STATE = 'SWITCH_CURSOR_STATE';
export const SWITCH_PREVIOUS_STAGE_CLICK = 'SWITCH_PREVIOUS_STAGE_CLICK';
export const SWITCH_NEXT_STAGE_CLICK = 'SWITCH_NEXT_STAGE_CLICK';
export const SWITCH_CURRENT_STAGE = 'SWITCH_CURRENT_STAGE';
export const SWITCH_CENTER_GAP = 'SWITCH_CENTER_GAP';
export const SWITCH_LIST_ACTIVE = 'SWITCH_LIST_ACTIVE';
export const SWITCH_PROJECT_ACTIVE = 'SWITCH_PROJECT_ACTIVE';
export const SWITCH_ABOUT_ACTIVE = 'SWITCH_ABOUT_ACTIVE';
export const SWITCH_CURRENT_SCROLL = 'SWITCH_CURRENT_SCROLL';
export const SWITCH_CENTER_GAP_DOWN = 'SWITCH_CENTER_GAP_DOWN';
export const SWITCH_STAGE_TRANSITION_DIRECTION =
  'SWITCH_STAGE_TRANSITION_DIRECTION';
